# Generated by Django 4.1 on 2022-08-21 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drainage',
            fields=[
                ('id', models.PositiveBigIntegerField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('start_latitude', models.DecimalField(decimal_places=16, default=0.0, max_digits=24)),
                ('start_longitude', models.DecimalField(decimal_places=16, default=0.0, max_digits=24)),
                ('end_latitude', models.DecimalField(decimal_places=16, default=0.0, max_digits=24)),
                ('end_longitude', models.DecimalField(decimal_places=16, default=0.0, max_digits=24)),
                ('width', models.FloatField(default=0.0)),
                ('above_high_tide', models.IntegerField(default=0)),
                ('below_high_tide', models.IntegerField(default=0)),
            ],
        ),
    ]
