# Generated by Django 4.1 on 2022-08-20 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PipeNetwork', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipeSensorReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_at', models.DateTimeField(auto_created=True)),
                ('flow_rate', models.FloatField(default=0.0, verbose_name='Flow Rate (m^3/s)')),
                ('water_level', models.FloatField(default=0.0, verbose_name='Water Level (%)')),
                ('pipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PipeNetwork.pipe')),
            ],
        ),
    ]
