# Generated by Django 4.1 on 2022-08-20 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pipe',
            fields=[
                ('id', models.PositiveBigIntegerField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('asset_id', models.CharField(db_index=True, max_length=24)),
                ('pipe_type', models.CharField(db_index=True, default='Unknown', max_length=64)),
                ('length', models.FloatField(default=0.0)),
                ('shape_length', models.FloatField(default=0.0)),
                ('district', models.CharField(db_index=True, max_length=128)),
                ('diameter', models.IntegerField(default=0)),
                ('material', models.CharField(db_index=True, default='Unknown', max_length=16)),
                ('depth', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='PipeGeometry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=16, default=0.0, max_digits=24)),
                ('longitude', models.DecimalField(decimal_places=16, default=0.0, max_digits=24)),
                ('level', models.FloatField(default=0.0)),
                ('pipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geometries', to='PipeNetwork.pipe')),
            ],
        ),
    ]
