# Generated by Django 4.1 on 2022-08-20 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PipeNetwork', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipegeometry',
            name='pipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geometries', to='PipeNetwork.pipe'),
        ),
    ]
