# Generated by Django 4.1 on 2022-08-20 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PipeNetwork', '0002_alter_pipegeometry_pipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipe',
            name='shape_length',
            field=models.FloatField(default=0.0),
        ),
    ]
